matrix:
  include:
  - language: node_js
    node_js: 6
    before_install:
      - cd client
  - language: php
    php: 5.6
    before_install:
      - cp .env.dist .env
      - cd server
    install:
      - composer install
    script:
      - composer test
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#wikimedia-commtech"
