version: '3'
services:
  web:
    links:
      - enwiki.db-replica
  enwiki.db-replica:
    build:
      context: .
      dockerfile: Dockerfile-replica-db
    env_file:
      - .env
    ports:
      - 4711:4711
